# Generated by Django 2.2.6 on 2019-10-23 04:30

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('value', models.CharField(blank=True, max_length=250, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Lawyer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address1', models.CharField(max_length=400, validators=[django.core.validators.RegexValidator(message='Enter Valid Address1', regex='^[A-Za-z0-9]*$')])),
                ('address2', models.CharField(max_length=400, validators=[django.core.validators.RegexValidator(message='Enter Valid Address2', regex='^[A-Za-z0-9]*$')])),
                ('city', models.CharField(max_length=128, validators=[django.core.validators.RegexValidator(message='City should only contain letters..', regex='[A-Za-z]{2}[a-z]+$')])),
                ('zipcode', models.CharField(max_length=128, validators=[django.core.validators.RegexValidator('^[0-9]{6}$', message='Enter Valid Zipcode')])),
                ('phone_number', models.CharField(max_length=128, validators=[django.core.validators.RegexValidator(message='Enter 10 digit number', regex='^[6|7|8|9]+[0-9]{9}$')])),
                ('license_id', models.CharField(max_length=128, validators=[django.core.validators.RegexValidator(message='Enter Valid License Id', regex='^[A-Za-z0-9]*$')])),
                ('year_admitted', models.CharField(choices=[('2019', '2019'), ('2018', '2018'), ('2017', '2017'), ('2016', '2016'), ('2015', '2015'), ('2014', '2014'), ('2013', '2013'), ('2012', '2012'), ('2011', '2011'), ('2010', '2010'), ('2009', '2009'), ('2008', '2008'), ('2007', '2007'), ('2006', '2006'), ('2005', '2005'), ('2004', '2004'), ('2003', '2003'), ('2002', '2002'), ('2001', '2001'), ('2000', '2000')], max_length=128)),
                ('profile_image', models.ImageField(upload_to='profile_images')),
            ],
        ),
        migrations.CreateModel(
            name='Practice_area',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('practice', models.CharField(blank=True, max_length=128, null=True)),
            ],
            options={
                'verbose_name_plural': 'Practice Area',
            },
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state_name', models.CharField(blank=True, max_length=400, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Sub_practice_area',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('practice_type', models.CharField(blank=True, max_length=128, null=True)),
                ('practice_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='lawyer.Practice_area')),
            ],
            options={
                'verbose_name_plural': 'Sub Practice Area',
            },
        ),
        migrations.CreateModel(
            name='Lawyer_practice_area',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub_practice_area', models.CharField(blank=True, max_length=200, null=True)),
                ('lawyer_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='lawyer.Lawyer')),
                ('practice_area', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='lawyer.Practice_area')),
            ],
        ),
        migrations.AddField(
            model_name='lawyer',
            name='license_in',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='license_id', to='lawyer.State'),
        ),
        migrations.AddField(
            model_name='lawyer',
            name='state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lawyer.State'),
        ),
        migrations.AddField(
            model_name='lawyer',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
