# Generated by Django 2.2.6 on 2019-10-24 08:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lawyer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lawyer',
            name='address1',
            field=models.CharField(max_length=400, validators=[django.core.validators.RegexValidator(message='Enter Valid Address1', regex='^[A-Za-z0-9]*[, .@\\/]*$')]),
        ),
        migrations.AlterField(
            model_name='lawyer',
            name='address2',
            field=models.CharField(max_length=400, validators=[django.core.validators.RegexValidator(message='Enter Valid Address2', regex='^[A-Za-z0-9]*[, .@\\/]*$')]),
        ),
    ]
