# Generated by Django 2.2.6 on 2019-10-16 07:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lawyer', '0002_auto_20191016_0709'),
    ]

    operations = [
        migrations.RenameField(
            model_name='state',
            old_name='state_name',
            new_name='state_name1',
        ),
    ]
