# Generated by Django 2.2.6 on 2019-10-24 08:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lawyer', '0002_auto_20191024_0822'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lawyer',
            name='zipcode',
            field=models.CharField(max_length=128, validators=[django.core.validators.RegexValidator(message='Enter Valid Zipcode', regex='^[0-9]{6}$')]),
        ),
    ]
