# Generated by Django 2.2.6 on 2019-10-16 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lawyer', '0005_auto_20191016_1050'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lawyer',
            name='year_admitted',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
