# Generated by Django 2.2.6 on 2019-10-24 09:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lawyer', '0005_auto_20191024_0829'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Data',
        ),
    ]
