# Generated by Django 2.2.6 on 2019-10-17 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lawyer', '0006_auto_20191016_1057'),
    ]

    operations = [
        migrations.AddField(
            model_name='lawyer',
            name='profile_image',
            field=models.ImageField(blank=True, upload_to='profile_images'),
        ),
        migrations.AlterField(
            model_name='lawyer',
            name='year_admitted',
            field=models.CharField(blank=True, choices=[('2019', '2019'), ('2018', '2018'), ('2017', '2017'), ('2016', '2016'), ('2015', '2015'), ('2014', '2014'), ('2013', '2013'), ('2012', '2012'), ('2011', '2011'), ('2010', '2010'), ('2009', '2009'), ('2008', '2008'), ('2007', '2007'), ('2006', '2006'), ('2005', '2005'), ('2004', '2004'), ('2003', '2003'), ('2002', '2002'), ('2001', '2001'), ('2000', '2000')], max_length=128, null=True),
        ),
    ]
