# Generated by Django 2.2.6 on 2019-11-01 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lawyer', '0007_review_lawyer'),
    ]

    operations = [
        migrations.AddField(
            model_name='review_lawyer',
            name='date_of_joining',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='review_lawyer',
            name='email',
            field=models.EmailField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='review_lawyer',
            name='first_name',
            field=models.CharField(blank=True, max_length=140),
        ),
    ]
