# Generated by Django 2.2.6 on 2019-11-01 09:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('lawyer', '0008_auto_20191101_0919'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review_lawyer',
            name='email',
        ),
        migrations.RemoveField(
            model_name='review_lawyer',
            name='first_name',
        ),
        migrations.AddField(
            model_name='review_lawyer',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
