# Generated by Django 2.2.6 on 2019-11-01 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lawyer', '0010_auto_20191101_1012'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review_lawyer',
            name='rating',
            field=models.IntegerField(blank=True),
        ),
    ]
