# Generated by Django 2.2.6 on 2019-11-04 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lawyer', '0011_auto_20191101_1149'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review_lawyer',
            name='date',
            field=models.DateField(auto_now=True, null=True),
        ),
    ]
