# Generated by Django 2.2.6 on 2019-11-04 06:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lawyer', '0012_auto_20191104_0509'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review_lawyer',
            name='date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='review_lawyer',
            name='rating',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='review_lawyer',
            name='review',
            field=models.CharField(max_length=5000, validators=[django.core.validators.RegexValidator(message='Enter proper review....', regex='^[A-Za-z0-9]+|,| |/|[A-Za-z]+)+[A-Za-z0-9]+|,| |$')]),
        ),
        migrations.AlterField(
            model_name='review_lawyer',
            name='title',
            field=models.CharField(max_length=228, validators=[django.core.validators.RegexValidator(message='Enter proper title....', regex='^[A-Za-z]+|,| |/|{2}[a-z0-9]{1,30}')]),
        ),
    ]
