# Generated by Django 2.2.6 on 2019-11-04 06:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lawyer', '0013_auto_20191104_0608'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review_lawyer',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='review_lawyer',
            name='lawyer_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lawyer.Lawyer'),
        ),
        migrations.AlterField(
            model_name='review_lawyer',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
