# Generated by Django 2.2.6 on 2019-11-04 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lawyer', '0014_auto_20191104_0608'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review_lawyer',
            name='review',
            field=models.CharField(max_length=5000),
        ),
        migrations.AlterField(
            model_name='review_lawyer',
            name='title',
            field=models.CharField(max_length=228),
        ),
    ]
