# Generated by Django 2.2.6 on 2019-11-06 10:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lawyer', '0016_review_lawyer_sub_practice_area'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review_lawyer',
            name='sub_practice_area',
        ),
    ]
