# Generated by Django 2.2.6 on 2019-11-29 10:11

from django.db import migrations
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('lawyer', '0020_auto_20191129_1006'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lawyer',
            name='profile_image',
            field=django_resized.forms.ResizedImageField(crop=None, force_format=None, keep_meta=True, quality=0, size=[149, 122], upload_to='profile_images'),
        ),
    ]
