# Generated by Django 2.2.6 on 2019-11-29 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lawyer', '0022_auto_20191129_1012'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lawyer',
            name='profile_image',
            field=models.ImageField(upload_to='profile_images'),
        ),
    ]
