# Generated by Django 2.2.6 on 2019-11-29 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lawyer', '0024_auto_20191129_1054'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lawyer',
            name='profile_image',
            field=models.ImageField(upload_to='profile_images'),
        ),
    ]
