# Generated by Django 2.2.6 on 2019-11-29 11:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lawyer', '0030_auto_20191129_1126'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lawyer',
            name='phone_number',
            field=models.CharField(max_length=128, validators=[django.core.validators.RegexValidator(message='Enter 10 digit number or must start with 6,7,8,9 digit', regex='^[6|7|8|9]+[0-9]{9}$')]),
        ),
    ]
